baseURL = "https://chengyaosun14.github.io/"
languageCode = "en-us"
title = "Chengyao Sun"
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = false

[params]
author = "Chengyao Sun"
description = "Personal Website"
dateFormat = "January 2, 2006"
avatarURL = "images/avatar.jpg"
hideFooter = true

[[params.social]]
name = "Email"
icon = "fa fa-envelope"
url = "mailto:your@email.com"

[[menu.main]]
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "CV"
url = "/cv/"
weight = 2